menu:
    Blog: /
    # Archive: /archives/
    GitHub: https://github.com/rogatty
    LinkedIn: https://www.linkedin.com/in/rogatty/
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
# google-analytics:
# FIXME
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2018
